config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  root 'static_pages#home'
  get '/generate', to: 'gengou#new'
  get '/about', to: 'static_pages#about'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/signout', to: 'sessions#destroy'
  get '/users/show'
  get '/post', to: 'posts#create'
  get '/loggedin', to: 'gengou#after_login'
  resources :posts, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 2 }

  def user
    return User.find(self.user_id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy

  def self.find_or_create_from_auth(auth)
      uid = auth[:uid]
      user_name = auth[:info][:name]
      nickname = auth[:info][:nickname]
      image_url = auth[:info][:image]

      self.find_or_create_by(uid: uid) do |user|
          user.user_name = user_name
          user.nickname = nickname
          user.image_url = image_url
      end
  end

  def feed
    Post.where("user_id = ?", id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?, :authenticate

  private

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find_by(uid: session[:user_id])
  end

  def logged_in?
    !!session[:user_id]
  end

  def authenticate
    return if logged_in?
    redirect_to root_path, alert: "ログインしてください"
  end
end

app/controllers/gengou_controller.rb
class GengouController < ApplicationController
  def new
    @gengous = ["大化", "白雉", "朱鳥", "大宝", "慶雲", "和銅", "霊亀", "養老", "神亀", "天平", "感宝", "勝宝", "宝字", "神護", "景雲", "宝亀", "天応", "延暦", "大同", "弘仁", "天長", "承和", "嘉祥", "仁寿", "斉衡", "天安", "貞観", "元慶", "仁和", "寛平", "昌泰", "延喜", "延長", "承平", "天慶", "天暦", "天徳", "応和", "康保", "安和", "天禄", "天延", "貞元", "天元", "永観", "寛和", "永延", "永祚", "正暦", "長徳", "長保", "寛弘", "長和", "寛仁", "治安", "万寿", "長元", "長暦", "長久", "寛徳", "永承", "天喜", "康平", "治暦", "延久", "承保", "承暦", "永保", "応徳", "寛治", "嘉保", "永長", "承徳", "康和", "長治","嘉承", "天仁", "天永", "永久", "元永", "保安", "天治", "大治", "天承", "長承", "保延", "永治", "康治", "天養", "久安", "仁平", "久寿", "保元", "平治", "永暦", "応保", "長寛", "永万", "仁安", "嘉応", "承安", "安元", "治承", "養和", "寿永", "元暦", "文治", "建久", "正治", "建仁", "元久", "建永", "承元", "建暦", "建保", "承久", "貞応", "元仁", "嘉禄", "安貞", "寛喜", "貞永", "天福", "文暦", "嘉禎", "暦仁", "延応", "仁治", "寛元", "宝治", "建長", "康元", "正嘉", "正元", "文応", "弘長", "文永", "建治", "弘安", "正応", "永仁", "正安", "乾元", "嘉元", "徳治", "延慶", "応長", "正和", "文保", "元応", "元亨", "正中", "嘉暦", "元徳", "元弘", "正慶", "建武", "延元", "暦応", "興国", "康永", "貞和", "正平", "観応", "文和", "延文", "康安", "貞治", "応安", "建徳", "文中", "永和", "天授", "康暦", "弘和", "永徳", "至徳", "元中", "嘉慶", "康応", "明徳", "応永", "正長", "永享", "嘉吉", "文安", "宝徳", "享徳", "康正", "長禄", "寛正", "文正", "応仁", "文明", "長享", "延徳", "明応", "文亀", "永正", "大永", "享禄", "天文", "弘治", "永禄", "元亀", "天正", "文禄","慶長", "元和", "寛永", "正保", "慶安", "承応", "明暦", "万治", "寛文", "延宝", "天和", "貞享", "元禄", "宝永", "正徳", "享保", "元文", "寛保", "延享", "寛延", "宝暦", "明和", "安永", "天明", "寛政", "享和", "文化", "文政", "天保", "弘化", "嘉永", "安政", "万延", "文久", "元治", "慶応", "明治", "大正", "昭和", "平成"]
    garapon
    @post_gengou = @gengou0 + @gengou1
    while @gengou0 == @gengou1 || @gengous.include?(@post_gengou) do
      garapon
      @post_gengou = @gengou0 + @gengou1
    end
    @gengou0_count = @gengous.count {|gengou| gengou.include?(@gengou0) }
    @gengou1_count = @gengous.count {|gengou| gengou.include?(@gengou1) }
  
#    @post = current_user.posts.build if logged_in?
  end

  def after_login
    @gengous = ["大化", "白雉", "朱鳥", "大宝", "慶雲", "和銅", "霊亀", "養老", "神亀", "天平", "感宝", "勝宝", "宝字", "神護", "景雲", "宝亀", "天応", "延暦", "大同", "弘仁", "天長", "承和", "嘉祥", "仁寿", "斉衡", "天安", "貞観", "元慶", "仁和", "寛平", "昌泰", "延喜", "延長", "承平", "天慶", "天暦", "天徳", "応和", "康保", "安和", "天禄", "天延", "貞元", "天元", "永観", "寛和", "永延", "永祚", "正暦", "長徳", "長保", "寛弘", "長和", "寛仁", "治安", "万寿", "長元", "長暦", "長久", "寛徳", "永承", "天喜", "康平", "治暦", "延久", "承保", "承暦", "永保", "応徳", "寛治", "嘉保", "永長", "承徳", "康和", "長治","嘉承", "天仁", "天永", "永久", "元永", "保安", "天治", "大治", "天承", "長承", "保延", "永治", "康治", "天養", "久安", "仁平", "久寿", "保元", "平治", "永暦", "応保", "長寛", "永万", "仁安", "嘉応", "承安", "安元", "治承", "養和", "寿永", "元暦", "文治", "建久", "正治", "建仁", "元久", "建永", "承元", "建暦", "建保", "承久", "貞応", "元仁", "嘉禄", "安貞", "寛喜", "貞永", "天福", "文暦", "嘉禎", "暦仁", "延応", "仁治", "寛元", "宝治", "建長", "康元", "正嘉", "正元", "文応", "弘長", "文永", "建治", "弘安", "正応", "永仁", "正安", "乾元", "嘉元", "徳治", "延慶", "応長", "正和", "文保", "元応", "元亨", "正中", "嘉暦", "元徳", "元弘", "正慶", "建武", "延元", "暦応", "興国", "康永", "貞和", "正平", "観応", "文和", "延文", "康安", "貞治", "応安", "建徳", "文中", "永和", "天授", "康暦", "弘和", "永徳", "至徳", "元中", "嘉慶", "康応", "明徳", "応永", "正長", "永享", "嘉吉", "文安", "宝徳", "享徳", "康正", "長禄", "寛正", "文正", "応仁", "文明", "長享", "延徳", "明応", "文亀", "永正", "大永", "享禄", "天文", "弘治", "永禄", "元亀", "天正", "文禄","慶長", "元和", "寛永", "正保", "慶安", "承応", "明暦", "万治", "寛文", "延宝", "天和", "貞享", "元禄", "宝永", "正徳", "享保", "元文", "寛保", "延享", "寛延", "宝暦", "明和", "安永", "天明", "寛政", "享和", "文化", "文政", "天保", "弘化", "嘉永", "安政", "万延", "文久", "元治", "慶応", "明治", "大正", "昭和", "平成"]
    @gengou0 = params[:gengou0] 
    @gengou1 = params[:gengou1]
    @post_gengou = @gengou0 + @gengou1
    @gengou0_count = @gengous.count {|gengou| gengou.include?(@gengou0) }
    @gengou1_count = @gengous.count {|gengou| gengou.include?(@gengou1) }
  
    @post = current_user.posts.build
  end
  

  private

  def garapon
    gara0 = rand(0..247)
    gara1 = rand(0..247)
    cross = rand(0..5)
    case cross
    when 0 then
      @gengou0 = @gengous[gara0].slice(1)
      @gengou1 = @gengous[gara1].slice(0)
    else
      @gengou0 = @gengous[gara0].slice(0)
      @gengou1 = @gengous[gara1].slice(1)
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
    user = User.find_by(uid: session[:user_id])
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "Posts created" 
      redirect_to '/generate'
    else
      @feed_items = []
      render 'static_pages/about'
    end
  end

  private

    def post_params
      params.require(:post).permit(:content, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
      user = User.find_or_create_from_auth(request.env['omniauth.auth'])
      session[:user_id] = user.uid
      flash[:notice] = "ユーザ認証が完了しました。"
      redirect_to loggedin_path(gengou0: params[:gengou0], gengou1: params[:gengou1])
      
  end

  def destroy
      reset_session
      flash[:notice] = "ログアウトしました。"
      redirect_to root_path
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @posts = Post.all
    @feed_items = Post.all.paginate(page: params[:page])
    if logged_in?
#      @post  = current_user.posts.build
#      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def about
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end

  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gengou_helper.rb
module GengouHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gengou/after_login.html.erb
<% provide(:title, '新元号候補生成') %>
<div class="center jumbotron">
  <h3>新元号候補</h3>
  <h1><%= @post_gengou %></h1>
  <table>
    <tr>
      <td><%= link_to "#{@gengou0}", "https://ja.wiktionary.org/wiki/#{@gengou0}", target: "_blank" %>：</td>
      <td>登場回数 &nbsp; <%= @gengou0_count %> &nbsp; </td>
      <td>回</td>
    </tr>
    <tr>
      <td><%= link_to "#{@gengou1}", "https://ja.wiktionary.org/wiki/#{@gengou1}", target: "_blank" %>：</td>
      <td>登場回数 &nbsp; <%= @gengou1_count %> &nbsp; </td>
      <td>回</td>
    </tr>
  </table>
  
  <% if logged_in? %>
    <p><%= button_to "応募", posts_path, params: {:post => {:content => @post_gengou}}, :method => :post, class: "btn btn-lg btn-primary"%></p>
  <% else %>
    <p><%= button_to "応募(Twitter認証が必要)", '/auth/twitter', :method => :get, class: "btn btn-lg btn-primary"%></p>
  <% end %>
  <p><%= button_to "再籤", generate_path, :method => :get, class: "btn btn-lg btn-primary"%></p>
  <% if flash[:notice] %>
    <div class="notice">
      <%= flash[:notice]%>
    </div>
  <% end %>
</div>

app/views/gengou/new.html.erb
<% provide(:title, '新元号候補生成') %>
<div class="center jumbotron">
  <h3>新元号候補</h3>
  <h1><%= @post_gengou %></h1>
  <table>
    <tr>
      <td><%= @gengou0 %>：</td>
      <td>登場回数 &nbsp; <%= @gengou0_count %> &nbsp; </td>
      <td>回</td>
    </tr>
    <tr>
      <td><%= @gengou1 %>：</td>
      <td>登場回数 &nbsp; <%= @gengou1_count %> &nbsp; </td>
      <td>回</td>
    </tr>
  </table>
  
  <p><%= button_to "応募", generate_path, :method => :get, class: "btn btn-lg btn-primary"%></p>
  <p><%= button_to "再籤", generate_path, :method => :get, class: "btn btn-lg btn-primary"%></p>
  <% if flash[:notice] %>
    <div class="notice">
      <%= flash[:notice]%>
    </div>
  <% end %>
</div>

app/views/gengou/show.html.erb
<%= user %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Gengou Dearby
    by silloi(<a href="https://www.twitter.com/silloi93">@silloi93</a>)
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <% if logged_in? %>
          <li><%= link_to 'Logout', '/signout' %></li>
        <% else %>
          <li><%= link_to 'Twitter Login', '/auth/twitter' %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <% if flash[:notice] %>
      <p><%= flash[:notice] %></p>
    <% end %>
    
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/posts/_post.html.erb
<tr id="post-<%= post.id %>">

  <td class="user"><%= link_to "@#{post.user.nickname}", "https://twitter.com/#{post.user.nickname}" %> &nbsp; </td>
  <td class="content"><%= post.content %> &nbsp; </td>
  <td class="timestamp">
    Posted <%= time_ago_in_words(post.created_at) %> ago.
  </td>
</tr>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="posts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="center jumbotron">
  <h1>Gengou Dearby</h1>
  <h2>Button Here</h2>
  <h2>Post Posted</h2>
  <ul class="posts">
  </ul>

  <p>Gengou Dearby Home</p>
  <%= link_to "Generate New Gengou", generate_path, class: "btn btn-lg btn-primary" %>
  <% if logged_in? %>
    <h1>こんにちは、<%=  current_user.user_name %>さん</h1>
    <p>ユーザー用ページです。</p>
    <% else %>
    <p>ログインしてください</p>
  <% end %>

  <div class="row">
    <div class="col-md-8">
      <h3>Post Feed</h3>
      <table>
        <tr class="title">
          <td>Twitter ID</td>
          <td>新元号</td>
          <td>投稿時刻</td>
        </tr>
        <%= render 'shared/feed' %>
      </table>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.nickname, user %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>